// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq13aoHcRfYaj1tNQdLp-5MZ31Jc8WKK8',
    appId: '1:971962537851:web:664870c8dcc483d9eacfde',
    messagingSenderId: '971962537851',
    projectId: 'quiz-app-cd1e5',
    authDomain: 'quiz-app-cd1e5.firebaseapp.com',
    databaseURL: 'https://quiz-app-cd1e5-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-cd1e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeShRNtrh3c9d5dV8hayqk-md4TEZPKw4',
    appId: '1:971962537851:android:6844258d2201dd9eeacfde',
    messagingSenderId: '971962537851',
    projectId: 'quiz-app-cd1e5',
    databaseURL: 'https://quiz-app-cd1e5-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-cd1e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu3hLJa-iUHbybwgl818PhIAFeuTfbJak',
    appId: '1:971962537851:ios:aeb70f82ee452971eacfde',
    messagingSenderId: '971962537851',
    projectId: 'quiz-app-cd1e5',
    databaseURL: 'https://quiz-app-cd1e5-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-app-cd1e5.appspot.com',
    iosBundleId: 'com.example.intelligentsia1',
  );
}
